---
- hosts: all
  become: true
  roles:
    - nginxinc.nginx
    - nginxinc.nginx_config
  vars:
    #nginx_state: absent
    #nginx_config_start: true

    nginx_config_http_upload_enable: true
    nginx_config_http_upload_src: conf.d.files/*.conf
    nginx_config_http_upload_dest: /etc/nginx/conf.d/

    nginx_config_cleanup: true
    # nginx_config_cleanup_paths:
    #   - directory:
    #       - /etc/nginx/conf.d
    #     recurse: false
    nginx_config_cleanup_files:
      - /etc/nginx/conf.d/default.conf