---
# add in all optional exporters except for perf and tcpstat which can cause high load problems
# also skip wifi
node_exporter_enabled_collectors: [buddyinfo, devstat, drbd, interrupts, ksmd, logind, meminfo_numa, mountstats, ntp, processes, qdisc, runit, supervisord, systemd]

# to make use of the textfile collector the directory must be set to a directory with write permissions enabled for node-exp
# node_exporter_textfile_dir: "/var/lib/node_exporter"

# optionally disable some collectors
# node_exporter_disabled_collectors: []